### ISSUE TITLE
Need to Display all Address details

### ISSUE THREAD

**Issue by ITLec** [ITLec/Dynamics365GoogleMap#1]
Need to Display all Address details, for example:
Country: CountryName
City: CityName
Area: AArea Name
Street: StreetName

**Comment by dina777** [comment]
[accessing_ui_in events_with_under_details.zip](https://github.com/ITLec/Dynamics365GoogleMap/files/1434487/accessing_ui_in.events_with_under_details.zip)
My Solution screen shot 
![image](https://user-images.githubusercontent.com/33133370/32280028-2d42d74c-bf23-11e7-8ba3-6809036ff2ba.png)
you have to create div in html then update it with the data 
like this in javascript
 document.getElementById("info").innerHTML="Latidute : "+latLng.lat()+"</br>"+"longitude : "+latLng.lng()+"</br>"+"Full Address :"+address.formatted_address+details;
it will be clear with my full example in attachment

**Comment by ITLec** [comment]
Good Example.
