### ISSUE TITLE
Need DropDown In Configuration Screen, so I can Select the default language for my organization. 

### ISSUE THREAD

**Issue by ITLec** [ITLec/Dynamics365GoogleMap#10]
we need a dropdown list as in this example: https://www.w3schools.com/tags/att_option_value.asp

But we should change the value& text as existed in this page  https://developers.google.com/maps/faq#languagesupport
Value: Language Code	& Text= Language

**Comment by dina777** [comment]
My solution screenshot
![image](https://user-images.githubusercontent.com/33133370/32280440-8cdd89f8-bf24-11e7-91b0-b659acda5ead.png)
my Full Example in attachment 
[Map_Lan.zip](https://github.com/ITLec/Dynamics365GoogleMap/files/1434504/Map_Lan.zip)

**Comment by ITLec** [comment]
I only need the blow code, thanks a lot Dina.

`<select id="lang" onchange="get_language();"><option value=""></option><option value="ar">Arabic</option><option value="bg">Bulgarian</option><option value="bn">Bengali</option><option value="ca">Catalan</option><option value="cs">Czech</option><option value="da">Danish</option><option value="de">German</option><option value="el">Greek</option><option value="en">English</option><option value="en-AU">English (Australian)</option><option value="en-GB">English (Great Britain)</option><option value="es">Spanish</option><option value="eu">Basque</option><option value="eu">Basque</option><option value="fa">Farsi</option><option value="fi">Finnish</option><option value="fil">Filipino</option><option value="fr">French</option><option value="gl">Galician</option><option value="gu">Gujarati</option><option value="hi">Hindi</option><option value="hr">Croatian</option><option value="hu">Hungarian</option><option value="id">Indonesian</option><option value="it">Italian</option><option value="iw">Hebrew</option><option value="ja">Japanese</option><option value="kn">Kannada</option><option value="ko">Korean</option><option value="lt">Lithuanian</option><option value="lv">Latvian</option><option value="ml">Malayalam</option><option value="mr">Marathi</option><option value="nl">Dutch</option><option value="no">Norwegian</option><option value="pl">Polish</option><option value="pt">Portuguese</option><option value="pt-BR">Portuguese (Brazil)</option><option value="pt-PT">Portuguese (Portugal)</option> <option value="ro">Romanian</option> <option value="ru">Russian</option><option value="sk">Slovak</option><option value="sl">Slovenian</option><option value="sr">Serbian</option><option value="sv">Swedish</option><option value="ta">Tamil</option><option value="te">Telugu</option><option value="th">Thai</option><option value="tl">Tagalog</option><option value="tr">Turkish</option><option value="uk">Ukrainian</option><option value="vi">Vietnamese</option><option value="zh-CN">Chinese (Simplified)</option><option value="zh-TW">Chinese (Traditional)</option></select>`

**Comment by ITLec** [comment]
I need to add a filter for the above option, so the output should be something like this 

![](https://4.bp.blogspot.com/-MAhlNLxHDxE/WcGpR9r5mYI/AAAAAAAAGFE/zQJWUZOLHwE-Rj76BOIK89nBS6Ns8i4QQCLcBGAs/s1600/WebResource.png)

I think the code should be something like this:-

`        <input type="text" id="txtFilter" onkeyup="filterOption()" placeholder="Search for entity..." title="Type in a name"  style="width: 250px">
        <br />
        <select id="allEntitiesOptionSet" size="4" onchange="allEntitiesOptionSet_OnChange()"  style="width: 250px"></select>`

and the Javascript should be something like this 
`
        function filterOption()
        {
            ITLecHTMLUtilsControlOption.Clear("allEntitiesOptionSet");
            if (ArrEntitiesLogicalName == null) {
                ArrEntitiesLogicalName = ITLecXrmUtilsMetaData.GetAllEntitiesLogicalName();
            }
            ArrEntitiesLogicalName.forEach(function (item) {
                var userInputLowerCase = ITLecHTMLUtilsControl.GetValue("txtFilter").toLowerCase();
                if (item.LogicalName.toLowerCase().indexOf(userInputLowerCase) != -1) {
                    ITLecHTMLUtilsControlOption.AddItem("allEntitiesOptionSet", item.LogicalName, item.LogicalName);
                }
            });
        }
`
Please send back to me the option set with filter

**Comment by ITLec** [comment]
This issue has been solved in this release. 

http://www.itlec.com/2018/02/ITLec-Google-Map-V-20180214.html
