### ISSUE TITLE
AutoComplete Search Does not work

### ISSUE THREAD

**Issue by ITLec** [ITLec/Dynamics365GoogleMap#3]

**Comment by dina777** [comment]
Auto Complete Search in google Map
my Solution screenshot 
![image](https://user-images.githubusercontent.com/33133370/32280349-3e31e380-bf24-11e7-9e3b-73af11aacdb4.png)
[accessing_ui_in events_with_under_details_with_search_tool_with_radio.zip](https://github.com/ITLec/Dynamics365GoogleMap/files/1434495/accessing_ui_in.events_with_under_details_with_search_tool_with_radio.zip)

**Comment by ITLec** [comment]
You are right, Google map api url must contains "&libraries=places".

The url should be something like this "**https://maps.googleapis.com/maps/api/js?key=your_key&libraries=places&callback=initMap**"
