### ISSUE TITLE
How To Set/ Change GoogleMap API Key?

### ISSUE THREAD

**Issue by ITLec** [ITLec/Dynamics365GoogleMap#4]

**Comment by ha3ant** [comment]
I cant find the answer!
How To Set/ Change Google Map API Key? #4

**Comment by ITLec** [comment]
Soon we will publish new version of GoogleMap, which support this feature.
Current version using anonymous service.

**Comment by ha3ant** [comment]
So when I use this solution in my 365,  the maps don't load in any entity and I get the below error when I want to use the dashboard:
"Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details."
after check the JavaScript console, I get this error: "MissingKeyMapError"

**Comment by ITLec** [comment]
The current version is working fine. 
Your error should be written in new ticket, not related to this one.
Please send to me Rasheed @ itlec .com more information about your organization so I can help you, and In case this issue is common, I will fix it to all the community.

**Comment by ITLec** [comment]
This issue has been solved in this release. http://www.itlec.com/2018/02/ITLec-Google-Map-V-20180214.html
