### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by bassetassen** [ITLec/Dynamics365GoogleMap#40]
Do you have any plans on giving this a license? As this is without a license now it is actually prohibited for us to use your solution.

See this link for more information: [https://choosealicense.com/](https://choosealicense.com/)

**Comment by ITLec** [comment]
Hi Sebastian,

This is free solution, feel free to use it.

Anyway, I will add licence file in the solution.

Thanks,
Rasheed

**Comment by ITLec** [comment]
https://github.com/ITLec/Dynamics365GoogleMap/blob/master/Licence.txt

**Comment by bassetassen** [comment]
Great, thanks 😄
