### ISSUE TITLE
How To Change Map Language "Localization"?

### ISSUE THREAD

**Issue by ITLec** [ITLec/Dynamics365GoogleMap#6]
Current version supports only English, so we need to support multiple languages.
Here is the list of all supported languages by Google
[https://developers.google.com/maps/faq#languagesupport](https://developers.google.com/maps/faq#languagesupport)

**Comment by dina777** [comment]
My Soluation screenshot
![image](https://user-images.githubusercontent.com/33133370/32280571-0476c54c-bf25-11e7-9767-66954bbc866e.png)
changing languages and support multiple languages
[Map_Lan.zip](https://github.com/ITLec/Dynamics365GoogleMap/files/1434515/Map_Lan.zip)

**Comment by ITLec** [comment]
I like you answer, However I think there are more realistic solutions, one of them is:-
1-Set the language from variable in the query string.
2- on the On_change event for the dropdown, redirect to the same html with different language value in the query string.
I like this solution because:-
1- no need for jquery
2- no javascript redundancy  as in your example.

**Comment by ITLec** [comment]
This issue has been solved in this release. http://www.itlec.com/2018/02/ITLec-Google-Map-V-20180214.html
